name = "EHTModel"
uuid = "aba06f68-8285-4329-b7bf-b3157c6bc00b"
authors = ["Paul Tiede", "Kazunori Akiyama"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EHTUtils = "9d0fa6a6-ae25-4c2e-8152-6c4b7f2016aa"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"

[compat]
Accessors = "0.1"
DocStringExtensions = "0.9"
julia = "1.7.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
